mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 8088
spring:
  application:
    name: fishbuild
  datasource:
#    driver-class-name: org.mysql.jdbc.Driver
    #      validation-query: select 'x' FROM DUAL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/0908?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: jkuy0.25
#    password: train2022
#    url: jdbc:postgresql://www.victorysoft.online:5432/db_train?currentSchema=public&useUnicode=true&characterEncoding=utf8
#    username: train2022

